#端口号配置
server:
  port: 8089
#数据库连接配置
#  spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#  spring.jackson.time-zone=GMT+8
spring:
  profiles:
    active: common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.124.121:3306/itmk-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#jwt配置
jwt:
  secret: com.itmk
  expiration: 3000000
itmk:
  loginUrl: /api/user/login
  imgUrl: /api/user/image