spring:
  redis:
    expire: 60000
    database: 0 # Redis使用的库
    host: 47.111.124.121
    port: 6379 #端口号
    password: 123456  #redis密码
    #    lettuce:
    #      pool:
    #        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
    #        max-wait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-idle: 8       # 连接池中的最大空闲连接
    #        min-idle: 1       # 连接池中的最小空闲连接
    timeout: 10000        #  连接超时时间（毫秒）
  cache:
    type: redis           #使用redis做缓存
#  mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl